github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: demo
    init: |
      python -m venv /workspace/.venv && \
      source /workspace/.venv/bin/activate && \
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b /workspace/bin
    command: |
      ln -s /workspace/bin/confluent /home/gitpod/.local/bin/confluent
      source /workspace/.venv/bin/activate
      confluent version
